version: '3'

networks:
  nginx_network:
    driver: bridge

services:
  goapp:
    build: api
    networks:
      - nginx_network

  front:
    build: front
    depends_on:
      - goapp
    networks:
      - nginx_network

  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on: 
      - goapp
      - front
    networks:
      - nginx_network
